### ISSUE TITLE
Date select contrast is low

### ISSUE THREAD

**Issue by nhunzaker** [dkniffin/active_material#3] opened 2015-04-30 16:27 UTC
![screen shot 2015-04-30 at 12 26 04 pm](https://cloud.githubusercontent.com/assets/590904/7417473/463a66a0-ef34-11e4-8992-53bf161807cb.png)

**Comment by dkniffin** [comment] 2023-07-06 01:01
@nhunzaker What type of input is this? I can't reproduce it

**Comment by nhunzaker** [comment] 2023-07-06 12:32
@dkniffin great question. It's been so long, and I do not remember the specific active-admin configuration to generate this.

It's possible that this code was transitioned over to the native date picker a while ago.

**Comment by dkniffin** [comment] 2023-07-06 13:37
Okay. I'll close this then. If anyone sees it again, I can reopen it.

**Closed by dkniffin** 2023-07-06 13:37 UTC
